language: java
jdk:
  - openjdk7
branches:
  only:
    - master
    - /^issue-.*$/
    - release
notifications:
  email:
    - tonny.madsen@gmail.com
script:
  - MVN_PROFILE=$([ "$(git status --branch --porcelain | sed -e '2,$d')" == "## release" ] && echo release || echo ci)
  - MVN_LAST_COMMIT="$(git log --pretty=oneline -1)"
  - export DISPLAY=:99.0
  - ${SHELL} /etc/init.d/xvfb start
  - git clone --quiet --branch gh-pages git://github.com/tonnymadsen/ui-bindings.git ui-bindings-pages
  - (cd com.rcpcompany.parent; mvn install -P${MVN_PROFILE} -Drepository.base.redirect='' -Dbuild.id="${TRAVIS_JOB_ID}" -Duibindings-build-user.password="superfly42" -DLAST_COMMIT="${MVN_LAST_COMMIT}")
