language: java
jdk:
  - openjdk6
env:
  - UPDATE_SITE=yes
matrix:
  include:
    - jdk: openjdk7
      env: UPDATE_SITE=no
    - jdk: oraclejdk7
      env: UPDATE_SITE=no
branches:
  only:
    - master
    - /^issue-.*$/
    - release
notifications:
  email:
    - tonny.madsen@gmail.com
script:
  - MVN_LAST_COMMIT="$(git log --pretty=oneline -1)"
  - echo "LAST_COMMIT='${MVN_LAST_COMMIT}'"
  - MVN_PROFILES=$([ "${MVN_LAST_COMMIT}" == "*RELEASE*" ] && echo release || echo ci)
  - if [ "${UPDATE_SITE}" == "yes" ]; then MVN_PROFILES="${MVN_PROFILES},update-site"; fi
  - export DISPLAY=":99.0"
  - ${SHELL} /etc/init.d/xvfb start
  - git clone --quiet --branch gh-pages git://github.com/tonnymadsen/ui-bindings.git ui-bindings-pages
  - (cd com.rcpcompany.parent; mvn install -P${MVN_PROFILES} -Drepository.base.redirect='' -Dbuild.id="${TRAVIS_JOB_ID}" -Duibindings-build-user.password="superfly42" -DLAST_COMMIT="${MVN_LAST_COMMIT}")
  