language: java
jdk:
  - openjdk7
branches:
  only:
    - master
    - /^issue-.*$/
    - release
notifications:
  email:
    - tonny.madsen@gmail.com
script:
  - export DISPLAY=:99.0
  - ${SHELL} /etc/init.d/xvfb start
  - git clone -b gh-pages git://github.com/tonnymadsen/ui-bindings.git ui-bindings-pages
  - (cd com.rcpcompany.parent; mvn install -Drepository.base.redirect='' -Dbuild.id="${TRAVIS_JOB_ID}")
  - (cd com.rcpcompany.parent; mvn deploy -Drepository.base.redirect='' -Dbuild.id="${TRAVIS_JOB_ID}")