language: java
jdk:
  - openjdk7
branches:
  only:
    - master
notifications:
  email:
    - tonny.madsen@gmail.com
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - mvn install