language: java
jdk:
  - openjdk7
branches:
  only:
    - master
notifications:
  email:
    - tonny.madsen@gmail.com
script:
  - export DISPLAY=:99.0
  - sh -e "/etc/init.d/xvfb start"
  - git clone -b gh-pages git@github.com:tonnymadsen/ui-bindings.git ui-bindings-pages
  - (cd com.rcpcompany.parent; mvn install)
  - (cd com.rcpcompany.parent; mvn deploy)